### ISSUE TITLE
we need way to copy the word and the definition

### ISSUE THREAD

**Issue by sfn101** [ashu-tosh-kumar/Wox.Plugin.eDict#2]
amazing work keep it up but it will be better if we can copy the word by hitting enter and the definition by hitting shift enter

**Comment by ashu-tosh-kumar** [comment]
Looks a good suggestion. It would be a small change. Will do that.

**Comment by sfn101** [comment]
any update yat?

**Comment by ashu-tosh-kumar** [comment]
I know it's a very late reply. I got busy with other projects. I have resumed working on this plugin and would actively maintain it in the foreseeable future. Should be able to have this functionality by EOW

**Comment by ashu-tosh-kumar** [comment]
Hi, as of yet, I don't see a viable and safe option to provide above functionality. I have opened a feature request with `Wox` that would allow me to implement above feature request.

More information: https://github.com/Wox-launcher/Wox/issues/3825

Closing this request for now.

**Comment by ashu-tosh-kumar** [comment]
Comment made above
