### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by arshadmdvr** [ashu-tosh-kumar/Wox.Plugin.eDict#3]
It's not working for me. It shows succesfully installed, but is not showing in plugin list

**Comment by ashu-tosh-kumar** [comment]
It's a very late reply. I got busy with other projects and have now resumed working on it and would actively maintain it in the foreseeable future. Can you please try installing again. I have made some changes and pumped the version to `v2.2.0`.

Will close this issue. If you still face any issue, please create another issue here with more details.
